name: Build and Check Project

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest

    env:
      ROOT_PASSWORD: root
      DB_NAME: niceDatabase
      DB_USER: user
      DB_PASSWORD: password

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Create and wait for database
      run: npm run create-db

    - name: Wait for healthchecks
      run: timeout 60s sh -c 'until docker ps | grep <CONTAINER_NAME> | grep -q healthy; do echo "Waiting for container to be healthy..."; sleep 2; done'


    - name: Run ESLint
      run: npm run lint

    - name: Run tests
      run: npm test

    - name: Shut down services
      run: docker-compose down
      if: always()