name: Build and Check Project

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest

    env:
      ROOT_PASSWORD: root
      DB_NAME: niceDatabase
      DB_USER: user
      DB_PASSWORD: password

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Create and wait for database
      run: |
        npm run create-db
        echo "Waiting for MySQL to be ready..."
        for i in {1..30}; do
          if docker-compose exec db mysql -h127.0.0.1 -uroot -p${{ env.ROOT_PASSWORD }} -e "SELECT 1" > /dev/null 2>&1; then
            echo "MySQL is ready!"
            break
          else
            echo "MySQL not ready yet. Waiting..."
            docker-compose logs db | tail -n 20
            sleep 5
          fi
        done

    - name: Run ESLint
      run: npm run lint

    - name: Run tests
      run: npm test

    - name: Shut down services
      run: docker-compose down
      if: always()